'use strict';
// 术语表 — 与包内 CONTEXT.md 的域词汇对齐，另补流程环节词与平台词。
// 报告正文中的术语一律通过 term() 链接到首页名词表，避免中英混杂无解释。
// 词条结构：{ id, zh, en, def: { zh, en } }——名称双语常驻（括注对照），释义随报告语言切换。

const TERMS = [
  // —— 域词汇（与 CONTEXT.md 对齐）——
  { id: 'ledger', zh: '台账', en: 'ledger', def: {
    zh: '人类可读的运行状态视图：头部（运行是否终结）、票表格、事件时间线、对账结论。由脚本从事件流与真相层（git、工作树、票状态）全量再生，任何人不手写手改。',
    en: 'A human-readable view of run state: header (whether the run has ended), ticket table, event timeline, reconciliation verdict. Fully regenerated by script from the event stream and the truth layer (git, worktrees, ticket state); never hand-written or hand-edited.',
  } },
  { id: 'event-stream', zh: '事件流', en: 'event stream', def: {
    zh: '只追加的 JSONL 机器事实文件，一行一条结构化事件，由脚本盖权威时间戳、单调序号与 git 锚点。它是编排器的唯一状态写面，也是本报告时间线与状态机的主要数据源。',
    en: 'An append-only JSONL machine-fact file: one structured event per line, stamped by script with authoritative timestamps, monotonic sequence numbers and git anchors. It is the orchestrator’s only state-writing surface, and the main data source for this report’s timeline and state machine.',
  } },
  { id: 'notes', zh: '编排笔记', en: 'orchestration notes', def: {
    zh: '散文记忆：过程叙事、教训、待决策问题、用户决定、暂停阶段与恢复说明，并引用处置证据。笔记不替代事件、git 或正式裁决；报告不解析散文生成已授权、已恢复、已解决或已批准的结论。',
    en: 'Prose memory for narrative, lessons, pending decisions, user decisions, pause stages and continuation context, with evidence references. Notes do not replace events, git or formal verdicts; the report does not interpret prose as authorization, resumption, resolution or approval.',
  } },
  { id: 'record', zh: '记账', en: 'record', def: {
    zh: '编排器通过脚本向事件流写入协议内结构化事实（派发、结算、裁决、修复、合并、升级、封账）的动作。人工暂停、用户决定和恢复上下文归编排笔记，不新增事件。',
    en: 'Writing protocol facts (dispatch, settle, verdict, fix, merge, escalate, seal) into the event stream via script. Human pauses, user decisions and continuation context belong in orchestration notes, not new events.',
  } },
  { id: 'close', zh: '封账', en: 'seal', def: {
    zh: '记账 close 事件：台账头部标记运行终结。completed 表示正常完成。显式 abandoned 表示用户放弃，不代表代码就绪或完整交付，不完成未完成票，也不解决历史问题。旧 close 缺少 outcome 时只表示封账结果未记录，不推断正常完成或放弃。封账后记账命令拒绝一切新事件。',
    en: 'Recording a close event: the ledger header marks the run as ended. completed records normal completion. Explicit abandoned means user abandonment, not code readiness or full delivery; it neither completes unfinished tickets nor resolves historical findings. An old close without outcome is shown as outcome not recorded, never inferred as completed or abandoned. After sealing, the record command rejects all new events.',
  } },
  { id: 'reconcile', zh: '对账', en: 'reconcile', def: {
    zh: '核验台账记录与实际世界（git、工作树、票文件状态）的差异。每次派发与合并前执行；发现漂移会逐条列出并阻断。',
    en: 'Checking ledger records against the real world (git, worktrees, ticket file state). Run before every dispatch and merge; any drift is listed item by item and blocks the step.',
  } },
  { id: 'flow-shape', zh: '流程形态', en: 'flow shape', def: {
    zh: '一次运行的流程开关组合：是否逐票评审、并发实现者数量。在运行初始化时冻结进事件流，中途改配置不影响进行中的运行。旧修复预算值仅作历史记录，不是有效上限。',
    en: 'The combination of flow switches for one run: whether each ticket is reviewed and the number of concurrent coders. Frozen into the event stream at run start; mid-run config changes never affect a run in progress. Old fix-budget values are historical records, not active limits.',
  } },

  // —— 流程环节词 ——
  { id: 'frontier', zh: '前沿', en: 'frontier', def: {
    zh: '当前所有阻塞已解除、可以立即派发的票的集合。编排器每轮从前沿取票并行派发，合并后重算前沿直至清空。',
    en: 'The set of tickets whose blockers are all cleared and that can be dispatched right now. Each wave the orchestrator takes tickets from the frontier and dispatches them in parallel, then recomputes the frontier after merges until it empties.',
  } },
  { id: 'dispatch', zh: '派发', en: 'dispatch', def: {
    zh: '编排器把一张票交给一个实现者子代理执行。每个实现者在独立的 git 工作树中工作，完成后报告提交锚点与测试结果。',
    en: 'Handing one ticket to a coder subagent for execution. Each coder works in its own git worktree and reports its commit anchor and test results when done.',
  } },
  { id: 'settled', zh: '实现结算', en: 'settle', def: {
    zh: '实现者完成一票后的锚定动作：从 git 真值确认提交存在，把提交 SHA 与工作树位置记入事件流，作为后续评审与合并的依据。',
    en: 'The anchoring act after a coder finishes a ticket: confirm the commit exists in git truth, then record the commit SHA and worktree location into the event stream as the basis for review and merge.',
  } },
  { id: 'verdict', zh: '评审裁决', en: 'verdict', def: {
    zh: '评审者对一票实现的完整正式结论：通过（approved）或需修改（changes_requested）。裁决与发现的问题清单一并记入事件流。正式评审轮次独立于修复次数；普通澄清或单问题撤回不替代批准。',
    en: 'A reviewer’s complete formal conclusion on one ticket’s implementation: approved or changes_requested. The verdict and its findings list are recorded into the event stream together. Formal review rounds are independent of fix attempts; ordinary clarification or withdrawal of a single finding does not replace approval.',
  } },
  { id: 'two-axis', zh: '双轴评审', en: 'two-axis review', def: {
    zh: '评审者从两个独立视角审查：规范轴（代码是否符合仓库既有规范）与需求轴（代码是否符合票面与 spec 的要求）。两轴可各派一个只读子代理并行执行。',
    en: 'The reviewer examines from two independent angles: the standards axis (does the code follow the repo’s existing conventions) and the spec axis (does it meet the ticket and the spec). Each axis may be dispatched to its own read-only subagent in parallel.',
  } },
  { id: 'fix-round', zh: '修复轮', en: 'fix round', def: {
    zh: '处理问题的一次修复尝试，通常把问题清单发回同一个实现者（续跑原会话）返工。编号表示尝试顺序，不设次数配额；一次评审后可多次修复，也可无新增修复再正式评审。',
    en: 'An attempt to fix a problem, usually by sending findings back to the same coder (resuming the original session). The number records attempt order, with no attempt quota; one review may be followed by multiple fixes, and a later formal review need not have a new fix.',
  } },
  { id: 'escalate', zh: '升级', en: 'escalate', def: {
    zh: '票移交用户决策的交接历史，既不是票完成，也不满足依赖或正常封账条件，不表示永久暂停。后续合并显示完成并保留升级历史；未合并时须结合事实、编排笔记与证据核对当前行动。原因以事件原文为准，不根据修复次数或旧预算推断。',
    en: 'The history of handing a ticket to the user for a decision: not ticket completion, dependency satisfaction, eligibility for normal sealing or a permanent pause. A later merge shows completion while keeping escalation history; without a merge, check current actions against facts, orchestration notes and evidence. Reasons come from the event, not fix counts or old budgets.',
  } },
  { id: 'integration-gate', zh: '集成测试门', en: 'integration gate', def: {
    zh: '每票合并到功能分支后立即运行全量测试套件。票级评审看不到的跨票集成问题在此暴露，红了就派无隔离修复者当场修。',
    en: 'The full test suite runs immediately after each ticket merges into the feature branch. Cross-ticket integration problems invisible to ticket-level review surface here; a red run dispatches a non-isolated fixer on the spot.',
  } },
  { id: 'final-review', zh: '终审', en: 'final review', def: {
    zh: '全部票合并后，对整条功能分支做一次整体双轴评审，结论为：可交付（ready）/ 可交付但需修（ready_with_fixes）/ 不可交付（not_ready）。',
    en: 'After all tickets merge, one whole-branch two-axis review of the entire feature branch, concluding: ready / ready_with_fixes / not_ready.',
  } },
  { id: 'anomaly', zh: '异常记录', en: 'anomaly', def: {
    zh: '协议中的不可变异常历史，可引用旧事件。处置办法与证据指针归编排笔记；历史本身不证明当前仍未解决，也不自动禁止收尾。报告保留有依据的补正或恢复标注与风险证据，无法机械核验时提示阅读笔记和证据，不从散文断言已解决；不伪造事实或绕过校验。',
    en: 'Immutable anomaly history in the protocol, optionally referencing an earlier event. Disposition and evidence pointers belong in orchestration notes; history alone neither establishes a current unresolved issue nor automatically blocks closeout. The report keeps supported correction or recovery annotations and risk evidence, and asks readers to inspect notes and evidence when disposition cannot be checked mechanically, without treating prose as resolution or bypassing validation.',
  } },

  // —— 平台词 ——
  { id: 'acceptance-contract', zh: '验收合同', en: 'acceptance contract', def: {
    zh: '派发时冻结的证据契约：实现者必须声明满足了哪些验收标准，并提交变更文件、新增测试、运行命令、验证输出与 no-staged-files 五项派发证据（每项空仓时用 [] 占位；residualRisks 是建议项，从不构成拒收理由）。这五项证据缺失或不合格会导致这次运行被拒收。',
    en: 'The evidence contract frozen at dispatch: the coder must state which acceptance criteria are satisfied and submit five pieces of dispatch evidence — changed files, new tests, run commands, verify output, and no-staged-files (each may be [] when empty; residualRisks is advisory and never grounds for rejection). Missing or unqualified evidence in these five causes the run to be rejected.',
  } },
  { id: 'structured-output', zh: '结构化输出', en: 'structured output', def: {
    zh: '子代理按约定模式返回的机器可读结果（如提交 SHA、测试结果、评审结论），区别于自由文本。编排器据此机械校验，不轻信散文。',
    en: 'The machine-readable result a subagent returns against an agreed schema (e.g. commit SHA, test results, review verdict), as distinct from free text. The orchestrator validates it mechanically and does not trust prose.',
  } },
  { id: 'worktree', zh: '工作树', en: 'worktree', def: {
    zh: 'git 工作树：同一仓库的独立检出目录。每个实现者在自己的工作树与分支上干活，互不干扰，合并时才汇入功能分支。',
    en: 'A git worktree: an independent checkout of the same repository. Each coder works in its own worktree and branch without interference, merging into the feature branch only at merge time.',
  } },
  { id: 'gate', zh: '门禁', en: 'gate', def: {
    zh: '派发时约定的验证命令（通常是全量测试套件）。实现者跑不绿就不算完成；合并后编排器会再跑一遍作为集成测试门。',
    en: 'The verification command agreed at dispatch (usually the full test suite). A coder is not done until it is green; after merging, the orchestrator runs it again as the integration gate.',
  } },
  { id: 'run', zh: '运行', en: 'run', def: {
    zh: '一次子代理执行的完整记录单元，有唯一运行 ID。同一运行可被续跑（resume）以完成修复轮，续跑共享同一运行 ID。',
    en: 'The complete record unit of one subagent execution, with a unique run ID. The same run can be resumed for fix rounds; a resume shares the same run ID.',
  } },
  { id: 'resume', zh: '续跑', en: 'resume', def: {
    zh: '让同一个子代理在保留的会话上下文中继续工作（典型场景：修复轮）。相对地，若保留的工作树已丢失则退回全新派发，事件流里两种路径都有记录。',
    en: 'Continuing the same subagent in its retained session context (typical case: fix rounds). If the retained worktree is gone it falls back to a fresh dispatch instead — both paths are recorded in the event stream.',
  } },
];

const TERM_INDEX = new Map();
for (const t of TERMS) {
  TERM_INDEX.set(t.id, t);
  TERM_INDEX.set(t.en.toLowerCase(), t);
  TERM_INDEX.set(t.zh, t);
}

// 查术语：优先按 id，其次英文名，再次中文名。未命中返回 null（调用方原样展示文本）。
function lookup(idOrName) {
  if (!idOrName) return null;
  return TERM_INDEX.get(idOrName) || TERM_INDEX.get(String(idOrName).toLowerCase()) || null;
}

module.exports = { TERMS, lookup };
